# â”Œâ”€â”€â”€â” â”Œâ”€â”€â”€â” â”Œâ”€â”€â”€â” â”Œâ”€â”€â”€â” â”Œâ”€â”€â”€â”
# â”‚ H â”‚ â”‚ E â”‚ â”‚ T â”‚ â”‚ F â”‚ â”‚ S â”‚
# â””â”€â”€â”€â”˜ â””â”€â”€â”€â”˜ â””â”€â”€â”€â”˜ â””â”€â”€â”€â”˜ â””â”€â”€â”€â”˜
#
# ğŸŒ HETFS LTD. - Code for a Brighter Future
# https://github.com/hetfs/dotfiles
#
# Platform-Specific Ansible Requirements for macOS
# =================================================

---
collections:
  - name: community.general
  - name: geerlingguy.mac

roles:
  - name: geerlingguy.homebrew
  - name: devsec.ssh-hardening
  - name: gantsign.visual-studio-code
  - name: elliotweiser.osx-command-line-tools
  - name: geerlingguy.dotfiles
