# â”Œâ”€â”€â”€â” â”Œâ”€â”€â”€â” â”Œâ”€â”€â”€â” â”Œâ”€â”€â”€â” â”Œâ”€â”€â”€â”
# â”‚ H â”‚ â”‚ E â”‚ â”‚ T â”‚ â”‚ F â”‚ â”‚ S â”‚
# â””â”€â”€â”€â”˜ â””â”€â”€â”€â”˜ â””â”€â”€â”€â”˜ â””â”€â”€â”€â”˜ â””â”€â”€â”€â”˜
#
# ğŸŒ HETFS LTD. - Code for a Brighter Future
# https://github.com/hetfs/dotfiles
#
# Platform-Specific Ansible Requirements for Arch Linux
# =====================================================

---
collections:
  - name: ansible.posix
  - name: community.general

roles:
  - name: devsec.ssh-hardening
  - name: oefenweb.sudo
  - name: gantsign.visual-studio-code
