# â”Œâ”€â”€â”€â” â”Œâ”€â”€â”€â” â”Œâ”€â”€â”€â” â”Œâ”€â”€â”€â” â”Œâ”€â”€â”€â”
# â”‚ H â”‚ â”‚ E â”‚ â”‚ T â”‚ â”‚ F â”‚ â”‚ S â”‚
# â””â”€â”€â”€â”˜ â””â”€â”€â”€â”˜ â””â”€â”€â”€â”˜ â””â”€â”€â”€â”˜ â””â”€â”€â”€â”˜
#
# ğŸŒ HETFS LTD. - Code for a Brighter Future
# https://github.com/hetfs/dotfiles
#
# Platform-Specific Ansible Requirements for Windows
# ==================================================

---
collections:
  - name: ansible.windows
  - name: community.windows
  - name: community.crypto
  - name: chocolatey.chocolatey

roles:
  # WinRM configuration and security
  - name: devsec.os-hardening
